"""Soul totems: the source `soul_totem` / `mini_soul_totem` FSMs, as a table.

A totem is a trigger box (layer 19, the damage layer) with a `Value` of hits.
While the Knight is near, each nail hit (`Check if Nail`: the damager's
`attackType` is 0) goes to `Hit`, which flings 8 or 9 `Soul Orb R` from the
global pool, shakes the camera (`EnemyKillShake`), takes one from `Value` and
waits 0.25 s; at zero it goes to `Depleted` and turns its collider off. Each
orb, on reaching the Knight, calls `HeroController.AddMPCharge(2)` (the
`SoulOrb.Zoom` coroutine, read from the installed CIL), so a hit is worth 16 or
18 SOUL. `Value` rides a `PersistentIntItem` marked `semiPersistent`, which the
game resets when the Knight rests at a bench.

The totem art is ordinary scenery the region cook already draws; the glow,
the orbs' flight and the particles are not presented. This reads the source
scenes and cooks nothing, so it is not a cooker input. Regenerate with

    .venv/bin/python host/soul_totems.py

which writes data/soul_totems.rs and .hkpsx/soul-totems.json.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'host'))

ONE = 65536
TEMPLATES = ('soul_totem', 'mini_soul_totem')
# `SoulOrb.Zoom`'s AddMPCharge argument.
SOUL_PER_ORB = 2


def _q(v):
    return round(v * ONE)


def survey(source, scenes):
    from scene import Scene
    from focus import action_fields
    import activation
    totems, refused = [], []
    for entry in scenes:
        sc = Scene(source, entry['file'])
        local = 0
        for sid, (typename, tree) in sorted(sc.objects.items()):
            if typename != 'PlayMakerFSM':
                continue
            try:
                fsm, variables, template = activation.instantiate(source, sc.file, tree)
            except Exception:
                continue
            if template not in TEMPLATES:
                continue
            gid = tree['m_GameObject']['m_PathID']
            name = sc.gos[gid]['m_Name']
            if not sc.active(gid):
                refused.append({'scene': entry['scene_name'], 'object': name, 'reason': 'inactive on a fresh save'})
                continue
            states = {s['name']: s for s in fsm['states']}
            hit = states['Hit']
            fling = wait = None
            for kind, index in activation._enabled(hit):
                fields = action_fields(hit['actionData'], index)
                plain = lambda v: v['value'] if isinstance(v, dict) and not v.get('useVariable') else v
                if kind == 'FlingObjectsFromGlobalPool':
                    fling = (plain(fields['spawnMin']), plain(fields['spawnMax']))
                elif kind == 'Wait':
                    wait = plain(fields['time'])
            value = variables.get('Value')
            if fling is None or wait is None or not isinstance(value, int) or value <= 0:
                raise ValueError(f'{entry["scene_name"]} {name}: unrecognized totem FSM')
            boxes = [t for i, (k, t) in sc.objects.items() if k == 'BoxCollider2D'
                     and t['m_GameObject']['m_PathID'] == gid]
            persist = [t for i, (k, t) in sc.objects.items() if k == 'PersistentIntItem'
                       and t['m_GameObject']['m_PathID'] == gid]
            if len(boxes) != 1 or not boxes[0]['m_IsTrigger'] or len(persist) != 1:
                raise ValueError(f'{entry["scene_name"]} {name}: expected one trigger box and one PersistentIntItem')
            matrix = sc.world(sc.go_transform[gid])
            sx, sy = abs(matrix[0][0]), abs(matrix[1][1])
            box = boxes[0]
            cx = matrix[0][3] + box['m_Offset']['x'] * matrix[0][0]
            cy = matrix[1][3] + box['m_Offset']['y'] * matrix[1][1]
            hw, hh = box['m_Size']['x'] * sx / 2, box['m_Size']['y'] * sy / 2
            totems.append({'scene': entry['scene_id'], 'scene_name': entry['scene_name'], 'local': local,
                           'object': name, 'source': f'{Path(sc.file.name).name}:{gid}', 'template': template,
                           'hits': value, 'orbs': list(fling), 'wait_ticks': round(wait * 60),
                           'semi_persistent': bool(persist[0]['semiPersistent']),
                           'bounds': [cx - hw, cy - hh, cx + hw, cy + hh]})
            local += 1
    return totems, refused


def rust(totems):
    lines = ['// Generated by host/soul_totems.py from the source soul totem FSMs.',
             '#[derive(Clone,Copy)] pub struct Totem {pub scene:u8,pub local:u8,pub bounds:[i32;4],pub hits:u8,pub orbs:[u8;2],pub wait_ticks:u8}',
             f'pub const SOUL_PER_ORB:u16={SOUL_PER_ORB};',
             f'pub static TOTEMS:[Totem;{len(totems)}]=[']
    for t in totems:
        b = ','.join(str(_q(v)) for v in t['bounds'])
        lines.append(f'Totem{{scene:{t["scene"]},local:{t["local"]},bounds:[{b}],hits:{t["hits"]},'
                     f'orbs:[{t["orbs"][0]},{t["orbs"][1]}],wait_ticks:{t["wait_ticks"]}}},')
    lines.append('];')
    return '\n'.join(lines) + '\n'


def main():
    from source import Source
    from quality import SCENE_TABLE
    totems, refused = survey(Source(), SCENE_TABLE)
    if any(not t['semi_persistent'] for t in totems):
        raise ValueError('a totem is fully persistent; the guest resets them all at a bench')
    (ROOT / 'data/soul_totems.rs').write_text(rust(totems))
    (ROOT / '.hkpsx/soul-totems.json').write_text(json.dumps({'totems': totems, 'refused': refused,
        'soul_per_orb': SOUL_PER_ORB,
        'limitations': ['The glow, the orb flight and the particles are not presented; the SOUL arrives on the hit.',
                        'The 8 or 9 orb count is a deterministic per-hit draw, not Unity RNG parity.']}, indent=2) + '\n')
    print(f'{len(totems)} soul totems: ' + ', '.join(f'{t["scene_name"]} {t["hits"]} hits' for t in totems), flush=True)


if __name__ == '__main__':
    main()
