"""Area and boss title cards: the source `Area Title Controller`s and `Titles`.

Each admitted scene may carry one `Area Title Controller`. Its FSM variables
say which area it announces (`Area Event`, a key into the `Titles` language
sheet's `<EVENT>_SUPER`, `_MAIN` and `_SUB` lines), whether it waits for the
Knight to enter its trigger box (`Wait for Trigger`), how long it pauses before
the card on a first and on a later visit, and whether it only speaks on a
revisit. The guest shows the card when the Knight enters an area other than
the one it last announced, which is the source's `GameManager` current-area
test. Boss names come from the same sheet (`FALSE_KNIGHT_MAIN` and so on) and
are shown by the boss's own code.

The text is drawn with the dialogue font the disc already carries, the main
line at twice its size; the source's Trajan face is not cooked. It reads the
source scenes and cooks nothing, so it is not a cooker input. Regenerate with

    .venv/bin/python host/title_cards.py

which writes data/title_cards.rs and .hkpsx/title-cards.json.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'host'))

ONE = 65536
# Boss titles the guest can ask for by name, from the same `Titles` sheet.
BOSSES = ('FALSE_KNIGHT', 'MAWLEK', 'BIGFLY')
# The dialogue font covers printable ASCII; the sheet uses typographic quotes.
ASCII = {'’': "'", '‘': "'", '“': '"', '”': '"', '–': '-', '—': '-'}


def ascii_text(text):
    out = ''.join(ASCII.get(c, c) for c in text)
    if any(not 32 <= ord(c) <= 126 for c in out):
        raise ValueError(f'title {text!r} has characters the dialogue font lacks')
    return out


def survey(source, scenes):
    from scene import Scene
    import activation
    rows, refused = [], []
    for entry in scenes:
        sc = Scene(source, entry['file'])
        found = []
        for sid, (typename, tree) in sorted(sc.objects.items()):
            if typename != 'PlayMakerFSM' or tree['fsm']['name'] != 'Area Title Controller':
                continue
            gid = tree['m_GameObject']['m_PathID']
            if not sc.active(gid):
                continue
            _, variables, _ = activation.instantiate(source, sc.file, tree)
            box = None
            if variables.get('Wait for Trigger'):
                boxes = [t for i, (k, t) in sc.objects.items() if k == 'BoxCollider2D'
                         and t['m_GameObject']['m_PathID'] == gid and t['m_IsTrigger']]
                if len(boxes) != 1:
                    refused.append({'scene': entry['scene_name'], 'reason': 'waits for a trigger it does not have'})
                    continue
                m = sc.world(sc.go_transform[gid]); b = boxes[0]
                cx = m[0][3] + b['m_Offset']['x'] * m[0][0]; cy = m[1][3] + b['m_Offset']['y'] * m[1][1]
                hw = b['m_Size']['x'] * abs(m[0][0]) / 2; hh = b['m_Size']['y'] * abs(m[1][1]) / 2
                box = [cx - hw, cy - hh, cx + hw, cy + hh]
            found.append({'scene': entry['scene_id'], 'scene_name': entry['scene_name'],
                          'event': variables['Area Event'], 'trigger': box,
                          'unvisited_ticks': round(variables['Unvisited Pause'] * 60),
                          'visited_ticks': round(variables['Visited Pause'] * 60),
                          'only_on_revisit': bool(variables['Only On Revisit'])})
        if len(found) > 1:
            raise ValueError(f'{entry["scene_name"]} carries {len(found)} area title controllers')
        rows += found
    return rows, refused


def texts(source, keys):
    import language
    sheet = language.sheet(source, 'Titles')
    out = []
    for key in keys:
        lines = [ascii_text(sheet.get(f'{key}_{part}', '')) for part in ('SUPER', 'MAIN', 'SUB')]
        if not lines[1]:
            raise ValueError(f'no {key}_MAIN title')
        out.append(lines)
    return out


def rust(areas, events, lines):
    esc = lambda s: s.replace('\\', '\\\\').replace('"', '\\"')
    out = ['// Generated by host/title_cards.py from the source area title controllers and the Titles sheet.',
           '#[derive(Clone,Copy)] pub struct Area {pub scene:u8,pub title:u8,pub trigger:Option<[i32;4]>,pub unvisited_ticks:u16,pub visited_ticks:u16,pub only_on_revisit:bool}',
           f'pub static TITLES:[[&str;3];{len(lines)}]=[' + ''.join(
               '[' + ','.join(f'"{esc(x)}"' for x in t) + '],' for t in lines) + '];']
    for i, key in enumerate(events):
        out.append(f'pub const {key}:u8={i};')
    out.append(f'pub static AREAS:[Area;{len(areas)}]=[')
    for a in areas:
        trig = 'None' if a['trigger'] is None else 'Some([' + ','.join(str(round(v * ONE)) for v in a['trigger']) + '])'
        out.append(f'Area{{scene:{a["scene"]},title:{events.index(a["event"])},trigger:{trig},'
                   f'unvisited_ticks:{a["unvisited_ticks"]},visited_ticks:{a["visited_ticks"]},'
                   f'only_on_revisit:{str(a["only_on_revisit"]).lower()}}},')
    out.append('];')
    return '\n'.join(out) + '\n'


def main():
    from source import Source
    from quality import SCENE_TABLE
    source = Source()
    areas, refused = survey(source, SCENE_TABLE)
    events = sorted({a['event'] for a in areas}) + [b for b in BOSSES]
    lines = texts(source, events)
    (ROOT / 'data/title_cards.rs').write_text(rust(areas, events, lines))
    (ROOT / '.hkpsx/title-cards.json').write_text(json.dumps({'areas': areas, 'refused': refused,
        'titles': dict(zip(events, lines)),
        'limitations': ['Drawn in the dialogue font, the main line at twice its size; the source Trajan face, ',
                        'its ornaments and its exact timing curves are not presented.']}, indent=2) + '\n')
    print(f'{len(areas)} area title controllers, {len(events)} titles: '
          + ', '.join(' '.join(x for x in l if x) for l in lines), flush=True)


if __name__ == '__main__':
    main()
