//! The enemies whose death the source keeps, as `data/actor_persistence.rs`.
//!
//! `HealthManager` hooks its object's `PersistentBoolItem`: a death writes the
//! item (`EnemyDeathEffects.RecieveDeathEvent` calls its `SaveState`), and a
//! scene that loads with the item set answers by marking the enemy dead and
//! deactivating it. The item's identity is its `persistentBoolData.id` and its
//! scene, and an empty id is replaced by the owner's name when the item starts,
//! so every placement of one name in a scene shares one state. `dontSave` items
//! never write, and `semiPersistent` ones are reset by a bench rest. All of that
//! is read off the installed `Assembly-CSharp.dll`'s IL (HealthManager.Awake,
//! `<Awake>b__69_1`, EnemyDeathEffects.RecieveDeathEvent, PersistentBoolItem
//! Start/SaveState/ResetState, GameManager.ResetSemiPersistentItems); none of it
//! is copied.
//!
//! Which placements: the ones the cook admits (`actors::scan`'s supported rows)
//! whose HealthManager object carries an enabled-or-not `PersistentBoolItem`
//! that saves. Families that keep a death of their own are left out: a boss
//! (the arena's `Activated`, `game/src/battle_gates.rs`) and the Blocker (its
//! terrain block, `game/src/blocker_terrain.rs`). An object merged in from an
//! additive scene (source id 100000 and up) is read from another file than the
//! one scanned here, and only the False Knight is admitted that way.
//!
//! The table is sorted by (scene, source id), one row per placement; the third
//! word is the state group (the order its first placement was met in) with
//! `hk_sim::SEMI_PERSISTENT` set when a bench rest resets it.

use crate::actors;
use crate::common::{component_records, err, Result};
use hk_unity::scene::Scene;
use hk_unity::{Source, Value};
use serde_json::Value as J;
use std::collections::HashMap;
use std::path::Path;

/// Families that keep a death of their own.
const OWN_PERSISTENCE: &[&str] = &["Blocker", "Mawlek", "FalseKnight", "GruzMother"];
/// The first source id of an object merged in from an additive scene.
const ADDITIVE_BASE: i64 = 100_000;

/// One persistent placement of a scene.
#[derive(Debug, PartialEq)]
pub struct Row {
    pub scene: usize,
    pub source_id: i64,
    /// Index of its state among the table's groups.
    pub group: usize,
    pub name: String,
    pub semi: bool,
}

fn flag(tree: &Value, key: &str) -> bool {
    tree.get(key).is_some_and(Value::truthy)
}

/// The persistent placements of one scene, groups numbered from `first_group`.
/// `groups` maps (scene, state id) to the group, extended as new states are met.
pub fn scene_rows(
    sc: &Scene,
    source: &Source,
    catalogue: &actors::Catalogue,
    scene: usize,
    groups: &mut HashMap<(usize, String), (usize, bool)>,
) -> Result<Vec<Row>> {
    let mut rows = Vec::new();
    for actor in actors::scan(sc, source, catalogue)? {
        if !actor.supported || actor.spec_source_id >= ADDITIVE_BASE {
            continue;
        }
        if actor.control.as_ref().is_some_and(|c| OWN_PERSISTENCE.contains(&c.0.as_str())) {
            continue;
        }
        let records = component_records(sc, actor.game_object);
        let Some(item) = records.iter().find(|r| r.1 == "PersistentBoolItem") else { continue };
        let tree = item.2;
        if flag(tree, "dontSave") {
            continue;
        }
        let semi = flag(tree, "semiPersistent");
        // `persistentBoolData.id` is empty in the scene files and becomes the
        // owner's name; an authored one would be used as it is.
        let authored = tree.get("persistentBoolData").and_then(|d| d.get("id")).and_then(Value::str).unwrap_or_default();
        let state = if authored.is_empty() { actor.name.clone() } else { authored };
        let next = groups.len();
        let (group, was_semi) = *groups.entry((scene, state.clone())).or_insert((next, semi));
        if was_semi != semi {
            return err(format!("{}: placements named {state} disagree about semiPersistent", sc.base.name));
        }
        rows.push(Row { scene, source_id: actor.spec_source_id, group, name: actor.name.clone(), semi });
    }
    Ok(rows)
}

/// The generated Rust source for a sorted set of rows.
pub fn render(rows: &[Row], groups: usize) -> String {
    let mut out = String::new();
    out.push_str("// Generated by hk-cook actor-persistence. Do not edit.\n");
    out.push_str("// Enemies whose source `PersistentBoolItem` keeps their death: (catalogue scene, source id,\n");
    out.push_str("// state group | SEMI_PERSISTENT when a bench rest resets it). Sorted by scene, then source id.\n");
    out.push_str(&format!("pub const GROUPS: usize = {groups};\n"));
    out.push_str("pub const PERSISTENT_ACTORS: &[hk_sim::PersistentActor] = &[\n");
    for r in rows {
        let word = r.group as u16 | if r.semi { 0x8000 } else { 0 };
        out.push_str(&format!("    ({}, {}, {:#06x}), // {}\n", r.scene, r.source_id, word, r.name));
    }
    out.push_str("];\n");
    out
}

pub fn main(root: &Path, source_dir: Option<&Path>) -> Result<()> {
    let source = match source_dir {
        Some(d) => Source::new(d),
        None => Source::from_doctor(root),
    }
    .map_err(|e| e.to_string())?;
    let text = std::fs::read(root.join("data/regions.json")).map_err(|e| format!("data/regions.json: {e}"))?;
    let report: J = serde_json::from_slice(&text).map_err(|e| format!("data/regions.json: {e}"))?;
    let scenes = report["scenes"].as_array().ok_or("report without scenes")?;
    let catalogue: Vec<(String, [f64; 4], String)> = scenes
        .iter()
        .map(|s| {
            let b: Vec<f64> = s["runtime_bounds"].as_array().map(|a| a.iter().map(|v| v.as_f64().unwrap_or(0.0)).collect()).unwrap_or_default();
            if b.len() != 4 {
                return err("scene without runtime_bounds");
            }
            Ok((s["file"].as_str().unwrap_or("").to_string(), [b[0], b[1], b[2], b[3]], s["scene_name"].as_str().unwrap_or("").to_string()))
        })
        .collect::<Result<_>>()?;
    let mut groups = HashMap::new();
    let mut rows = Vec::new();
    for (index, s) in scenes.iter().enumerate() {
        let scene = s["scene_id"].as_u64().unwrap_or(index as u64) as usize;
        let sc = Scene::new(&source, s["file"].as_str().unwrap_or("")).map_err(|e| e.to_string())?;
        rows.extend(scene_rows(&sc, &source, &catalogue, scene, &mut groups)?);
    }
    rows.sort_by_key(|r| (r.scene, r.source_id));
    if groups.len() >= 0x8000 {
        return err("more persistent states than a group word holds");
    }
    let path = root.join("data/actor_persistence.rs");
    std::fs::write(&path, render(&rows, groups.len())).map_err(|e| format!("{}: {e}", path.display()))?;
    println!("actor persistence: {} placements in {} states, {} semi-persistent", rows.len(), groups.len(), rows.iter().filter(|r| r.semi).count());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rows_render_as_the_sorted_table_the_guest_searches() {
        let rows = vec![
            Row { scene: 2, source_id: 125050, group: 0, name: "Zombie Runner 1".into(), semi: false },
            Row { scene: 19, source_id: 77, group: 1, name: "Hatcher".into(), semi: true },
        ];
        let text = render(&rows, 2);
        assert!(text.contains("pub const GROUPS: usize = 2;"));
        assert!(text.contains("(2, 125050, 0x0000), // Zombie Runner 1"));
        assert!(text.contains("(19, 77, 0x8001), // Hatcher"));
    }
}
